CREATE TABLE `TAX_TRAVEL_TRACKER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CREATED_AT` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`CREATED_BY` VARCHAR(200),
	`TRAVEL_TIME` DATE,
	`TRAVEL_FROM` VARCHAR(500),
	`TRAVEL_TO` VARCHAR(500),
	`TRAVEL_DISTANCE` INT,
	`ESTIMATED_TAX_DEDUCTIONS` INT,
	PRIMARY KEY (`ID`)
);